server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于与binding整合
          type: rabbit # 消息中间件类型
          environment: # 配置rabbitmq的环境
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务整合处理
        input: # 通道名称，input表示本服务是消息消费者
          destination: studyExchange # 表示要使用的Exchange名称
          content-type: application/json # 设置消息类型，这里定义的是json，文本则使用text/plain
          binder: defaultRabbit # 配置要绑定的消息服务的设置
          group: rhythmA #分组，同组内的服务会竞争一条消息，不同组的服务可重复消费，服务重启后会消费队列中未消费的消息




eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ # 指定eureka server地址
  instance:
    instance-id: cloudStreamConsumer8802  # 配置服务的主机名
    prefer-ip-address: true # 显示服务ip地址
