server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver  # mysql驱动包
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/cloud_payment_service?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  cloud:
    zookeeper:
      connect-string: localhost:2181 # zookeeper服务注册中心地址，集群配置用逗号隔开

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # mapper文件路径
  type-aliases-package: com.rhythm.entities # 所有Entity别名类所在包


